### ISSUE TITLE
Not working in KiCad 9.0

### ISSUE THREAD

**Issue by rickbassham** [gauravmm/HierarchicalPcb#32]
I get the following error when updating a board with the plugin in KiCad 9.0:

```
Traceback (most recent call last):

File "/Users/rick/Documents/KiCad/9.0/3rdparty/plugins/com_github_gauravmm_hierarchicalpcb/hplugin.py", line 54, in Run
RunActual(cfg, wx_frame, board)

File "/Users/rick/Documents/KiCad/9.0/3rdparty/plugins/com_github_gauravmm_hierarchicalpcb/hplugin.py", line 65, in RunActual
enforce_position(hD, board)

File "/Users/rick/Documents/KiCad/9.0/3rdparty/plugins/com_github_gauravmm_hierarchicalpcb/placement.py", line 269, in enforce_position
err_footprints = enforce_position_footprints(

File "/Users/rick/Documents/KiCad/9.0/3rdparty/plugins/com_github_gauravmm_hierarchicalpcb/placement.py", line 459, in enforce_position_footprints
transform.footprint(fp, fp_target)

File "/Users/rick/Documents/KiCad/9.0/3rdparty/plugins/com_github_gauravmm_hierarchicalpcb/placement.py", line 102, in footprint
fp_mutate.SetZoneConnection(fp_template.GetZoneConnection())

AttributeError: 'FOOTPRINT' object has no attribute 'SetZoneConnection'
```

**Comment by rickbassham** [comment]
Looks like it should now be `SetLocalZoneConnection`:

https://gitlab.com/kicad/code/kicad/-/commit/ee3be0802c5a10092b8d983d5c19da76ff144db8#27644b18760cdaea7b4165a44cc51040214836c6_274_266

**Comment by OllyFunkster** [comment]
I changed SetZoneConnection / GetZoneConnection to SetLocalZoneConnection / GetLocalZoneConnection, and now instead of the error KiCAD just segfaults after a couple of seconds.

Backtrace (is there a way to get debugging symbols for _pcbnew.kiface using GDB's auto-download or do I need to build from source?):
```
Thread 1 "kicad" received signal SIGSEGV, Segmentation fault.
0x00007fffbea3ae1b in ?? () from /usr/bin/_pcbnew.kiface
(gdb) bt
#0  0x00007fffbea3ae1b in ??? () at /usr/bin/_pcbnew.kiface
#1  0x00007ffff379654a in cfunction_call (func=0x7fffbc30a340, args=0x7fffb617a540, kwargs=0x0)
    at Objects/methodobject.c:551
#2  0x00007ffff375d60c in _PyObject_MakeTpCall
    (tstate=0x7ffff3b26e90 <_PyRuntime+283024>, callable=0x7fffbc30a340, args=<optimized out>, nargs=<optimized out>, keywords=0x0) at Objects/call.c:242
#3  0x00007ffff377705c in _PyEval_EvalFrameDefault
    (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/generated_cases.c.h:813
#4  0x00007ffff37d0dfe in _PyEval_EvalFrame
    (tstate=0x7ffff3b26e90 <_PyRuntime+283024>, frame=<optimized out>, throwflag=0)
    at ./Include/internal/pycore_ceval.h:119
#5  _PyEval_Vector
    (tstate=0x7ffff3b26e90 <_PyRuntime+283024>, func=0x7fffb5b90180, locals=0x0, args=0x7fffffffcd98, argcount=1, kwnames=0x0) at Python/ceval.c:1812
#6  _PyFunction_Vectorcall (func=0x7fffb5b90180, stack=0x7fffffffcd98, nargsf=1, kwnames=0x0)
    at Objects/call.c:413
#7  _PyObject_VectorcallTstate
    (tstate=0x7ffff3b26e90 <_PyRuntime+283024>, callable=0x7fffb5b90180, args=0x7fffffffcd98, nargsf=1, kwnames=0x0) at ./Include/internal/pycore_call.h:168
#8  method_vectorcall (method=<optimized out>, args=0x0, nargsf=0, kwnames=0x0) at Objects/classobject.c:70
#9  0x00007ffff3758685 in _PyObject_VectorcallTstate
    (tstate=0x7ffff3b26e90 <_PyRuntime+283024>, callable=0x7fffb7b8be00, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at ./Include/internal/pycore_call.h:168
#10 0x00007fffbea9aadc in ??? () at /usr/bin/_pcbnew.kiface
#11 0x00007fffbea9e5c9 in ??? () at /usr/bin/_pcbnew.kiface
#12 0x00007ffff717465f in wxEvtHandler::ProcessEventIfMatchesId (entry=..., handler=<optimized out>, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1482
#13 0x00007ffff7176b76 in wxEvtHandler::SearchDynamicEventTable (this=this@entry=0x5555574ed8c0, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1952
#14 0x00007ffff7176ede in wxEvtHandler::TryHereOnly (this=0x5555574ed8c0, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1675
#15 0x00007fffbef660be in ??? () at /usr/bin/_pcbnew.kiface
#16 0x00007ffff717482e in wxEvtHandler::DoTryChain (this=<optimized out>, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1644
#17 0x00007ffff7176fb0 in wxEvtHandler::ProcessEventLocally (this=<optimized out>, event=<optimized out>)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1612
#18 0x00007ffff71770bb in wxEvtHandler::ProcessEvent (this=0x5555574eded0, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1585
#19 0x00007ffff7807a80 in wxWindowBase::TryAfter (this=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/include/wx/window.h:862
#20 0x00007ffff7f53804 in wxAuiToolBar::OnLeftUp (this=0x555557d5de90, evt=<optimized out>)
    at /usr/src/debug/wxwidgets/wxWidgets/src/aui/auibar.cpp:2696
#21 0x00007ffff717465f in wxEvtHandler::ProcessEventIfMatchesId
    (entry=<optimized out>, handler=handler@entry=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1482
#22 0x00007ffff7175b44 in wxEventHashTable::HandleEvent
    (this=<optimized out>, event=..., self=self@entry=0x555557d5de90)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1087
#23 0x00007ffff7176f08 in wxEvtHandler::TryHereOnly (this=this@entry=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1679
#24 0x00007ffff7176f90 in wxEvtHandler::TryBeforeAndHere (this=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/include/wx/event.h:4011
#25 wxEvtHandler::ProcessEventLocally (this=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1612
#26 0x00007ffff71770bb in wxEvtHandler::ProcessEvent (this=0x555557d5de90, event=...)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1585
#27 0x00007ffff71778e2 in wxEvtHandler::SafelyProcessEvent (this=<optimized out>, event=<optimized out>)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/event.cpp:1701
#28 0x00007ffff7970db9 in gtk_window_button_release_callback (gdk_event=0x5555578633e0, win=0x555557d5de90)
    at /usr/src/debug/wxwidgets/wxWidgets/src/gtk/window.cpp:1933
#29 0x00007ffff56b8815 in _gtk_marshal_BOOLEAN__BOXED
    (closure=0x555557d5f550, return_value=0x7fffffffd960, param_values=0x7fffffffd9f0, marshal_data=<optimized out>, invocation_hint=<optimized out>, n_param_values=<optimized out>) at gtk/gtkmarshalers.c:84
#30 0x00007ffff72c6812 in g_closure_invoke
    (closure=0x555557d5f550, return_value=0x7fffffffd960, n_param_values=2, param_values=0x7fffffffd9f0, invocation_hint=0x7fffffffd940) at ../glib/gobject/gclosure.c:833
#31 0x00007ffff72f6f85 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x7fffffffdb00, detail=detail@entry=0, instance=instance@entry=0x5555577460e0, emission_return=emission_return@entry=0x7fffffffdb80, instance_and_params=instance_and_params@entry=0x7fffffffd9f0) at ../glib/gobject/gsignal.c:3902
#32 0x00007ffff72e748f in signal_emit_valist_unlocked
    (instance=instance@entry=0x5555577460e0, signal_id=signal_id@entry=83, detail=detail@entry=0, var_args=var_args@entry=0x7fffffffdc70) at ../glib/gobject/gsignal.c:3547
#33 0x00007ffff72e7f72 in g_signal_emit_valist
    (instance=0x5555577460e0, signal_id=83, detail=0, var_args=var_args@entry=0x7fffffffdc70) at ../glib/gobject/gsignal.c:3277
#34 0x00007ffff72e8034 in g_signal_emit
    (instance=instance@entry=0x5555577460e0, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3597
#35 0x00007ffff599a8ed in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0x5555577460e0 [wxPizza], event=0x5555578633e0)
    at ../gtk/gtk/gtkwidget.c:7822
#36 0x00007ffff58269e5 in propagate_event_up (widget=0x5555577460e0 [wxPizza], event=<optimized out>, topmost=<optimized out>)
    at ../gtk/gtk/gtkmain.c:2588
#37 propagate_event
    (widget=widget@entry=0x5555577460e0 [wxPizza], event=event@entry=0x5555578633e0, captured=captured@entry=0, topmost=topmost@entry=0x0) at ../gtk/gtk/gtkmain.c:2691
#38 0x00007ffff5826b31 in gtk_propagate_event (widget=0x5555577460e0 [wxPizza], event=0x5555578633e0)
    at ../gtk/gtk/gtkmain.c:2725
#39 0x00007ffff58277bb in gtk_main_do_event (event=<optimized out>) at ../gtk/gtk/gtkmain.c:1921
#40 gtk_main_do_event (event=<optimized out>) at ../gtk/gtk/gtkmain.c:1691
#41 0x00007ffff733b457 in _gdk_event_emit (event=0x5555578633e0) at ../gtk/gdk/gdkevents.c:73
#42 _gdk_event_emit (event=0x5555578633e0) at ../gtk/gdk/gdkevents.c:67
#43 0x00007ffff7399fe0 in gdk_event_source_dispatch.lto_priv () at ../gtk/gdk/x11/gdkeventsource.c:354
#44 0x00007ffff6b06104 in g_main_dispatch (context=0x555555b1e4f0) at ../glib/glib/gmain.c:3398
#45 0x00007ffff6b69d57 in g_main_context_dispatch_unlocked (context=0x555555b1e4f0) at ../glib/glib/gmain.c:4249
#46 g_main_context_iterate_unlocked.isra.0
    (context=0x555555b1e4f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4314
#47 0x00007ffff6b06de7 in g_main_loop_run (loop=0x55555719b6d0) at ../glib/glib/gmain.c:4516
#48 0x00007ffff5824dff in gtk_main () at ../gtk/gtk/gtkmain.c:1329
#49 0x00007ffff7946ec6 in wxGUIEventLoop::DoRun (this=0x555555b42140)
    at /usr/src/debug/wxwidgets/wxWidgets/src/gtk/evtloop.cpp:61
#50 0x00007ffff70b6a8b in wxEventLoopBase::Run (this=0x555555b42140)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/evtloopcmn.cpp:87
#51 0x00007ffff70914e7 in wxAppConsoleBase::MainLoop (this=0x555555aeeee0)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/appbase.cpp:381
#52 0x00005555556894f4 in APP_KICAD::OnRun (this=<optimized out>) at /usr/src/debug/kicad/kicad/kicad/kicad.cpp:496
#53 0x00007ffff70f5b31 in wxEntry (argc=@0x7ffff7252624: 1, argv=<optimized out>)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/init.cpp:497
#54 0x00007ffff70f5be4 in wxEntry (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/wxwidgets/wxWidgets/src/common/init.cpp:509
#55 0x000055555565f26f in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/kicad/kicad/kicad/kicad.cpp:592

```

**Comment by OllyFunkster** [comment]
Okay so, it's crashing at placement.py line 389, `targetFootprint.SetReference(originalReference)`

Commenting this line out, it then makes it much further but then crashes at line 231, `pcbnew.Refresh()`

Commenting out line 455, `copy_footprint_fields(sourceFootprint, targetFootprint, transform)` prevents it crashing, and the tracks get replicated on a very basic test project, however I assume that copying the fields is actually necessary for the plugin to do everything expected of it.

**Comment by hynek2001** [comment]
> Okay so, it's crashing at placement.py line 389, `targetFootprint.SetReference(originalReference)`
> 
> Commenting this line out, it then makes it much further but then crashes at line 231, `pcbnew.Refresh()`
> 
> Commenting out line 455, `copy_footprint_fields(sourceFootprint, targetFootprint, transform)` prevents it crashing, and the tracks get replicated on a very basic test project, however I assume that copying the fields is actually necessary for the plugin to do everything expected of it.

interesting. For me with latest nightly it was enough to do only "I changed SetZoneConnection / GetZoneConnection to SetLocalZoneConnection / GetLocalZoneConnection"   i am using python 3.12 on linux/ubuntu

**Comment by OfficialDyray** [comment]
Schematic replication was Implemented in KiCad 9 via the [multichannel tool](https://forum.kicad.info/t/multi-channel-tool/55809), so this plugin is not necessary.

**Comment by OfficialDyray** [comment]
I am seeing a similar crash as Olly. From my testing the line [placement.py:359](https://github.com/gauravmm/HierarchicalPcb/blob/999d3938cc3d3e61fa61edb82425e912530cfe61/placement.py#L359) is the issue. I haven't been able to find a way to delete a field from a footprint without causing a crash. ( sometimes it looks like it works, but after a pcbnew.refresh() or selecting the footprint it will crash).

Maybe trying out the new IPC API will get rid of the SWIG weirdness...

**Comment by OfficialDyray** [comment]
@tytgatlieven When I said schematic replication, I meant pcb/layout replication. You may still prefer to replicate layouts with this plugin, but the multichannel tool should have better support and less bugs (especially as kicad matures).

**Comment by paul-fornage** [comment]
I didn't think to check commits because I figured if the 9.0 support was added, it would have been released.

I independently arrived at the solution of using `SetLocalZoneConnection`/`GetLocalZoneConnection`, and everything works, no crashes. (Will post an update if I run into problems)

```
KiCad x86_64 on x86_64

Version: 9.0.4, release build

Libraries:
	wxWidgets 3.2.8
	FreeType 2.14.1
	HarfBuzz 11.5.0
	FontConfig 2.17.1
	libcurl/8.16.0 OpenSSL/3.5.3 zlib/1.3.1 brotli/1.1.0 zstd/1.5.7 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.67.1 nghttp3/1.12.0

Platform: Arch Linux, 64 bit, Little endian, wxGTK, Wayland, Hyprland, wayland

Build Info:
	Date: Sep 21 2025 21:39:27
	wxWidgets: 3.2.8 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.88.0
	OCC: 7.9.1
	Curl: 8.16.0
	ngspice: 45
	Compiler: GCC 15.2.1 with C++ ABI 1020

Build settings:
	KICAD_USE_EGL=ON
	KICAD_IPC_API=ON

Locale: 
	Lang: en_US
	Enc: UTF-8
	Num: 1,234.5
	Encoded кΩ丈: D0BACEA9E4B888 (sys), D0BACEA9E4B888 (utf8)
```

**Comment by gauravmm** [comment]
Hey, this project has been superseded by https://github.com/OfficialDyray/ProjectInstances/ Please use that instead!
